### ISSUE TITLE
404 error on tigervnc.org homepage when selecting link to mail archive regarding project creation

### ISSUE THREAD

**Issue by HeWhoWatches** [TigerVNC/tigervnc.github.io#8]
Not really a bug exactly, but the link on the tigervnc.org home page to the mail archive (regarding the motivation for creating the project) seems to be a dead link, returning a 404 error.

This is the specific bit of HTML:
```
TigerVNC was originally based on the (never-released) VNC 4 branch of
<a href="http://www.tightvnc.com/">TightVNC</a>. More information
regarding the motivation for creating this project can be found in the
<a href="http://mid.mail-archive.com/alpine.LFD.2.00.0902271116020.25749@maggie.lkpg.cendio.se">project
announcement</a>.
```

Would this be the correct link?
https://www.mail-archive.com/vnc-list@realvnc.com/msg27308.html

Thanks,
Rob

**Comment by CendioOssman** [comment]
Works fine for me. Are you perhaps running some extension that is messing up the URL, like in #7?

**Comment by HeWhoWatches** [comment]
Well I'll be. That's exactly what it was, turning the extension off or adding "http://mid.mail-archive.com" to the unprotected sites list in the extension settings fixes the problem. I think I will opt for removing it - I'm not a fan of extensions "helping" without making it clear what they're doing. Thanks for checking, sorry for the false alarm!

**Comment by CendioOssman** [comment]
No problem. It's a bit of a bug that mail archive hasn't enabled https for that service.
